fst: Self registering FS -- WIP

diff --git a/fst/templates/configmap.yaml b/fst/templates/configmap.yaml
--- a/fst/templates/configmap.yaml
+++ b/fst/templates/configmap.yaml
@@ -1,49 +1,269 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: {{ include "fst.fullname" . }}-config
+  name: {{ include "fst.fullname" . }}-cfgmap-xrd-cf-fst
   labels:
     {{- include "fst.labels" . | nindent 4 }}
 data:
-  configure.sh: |
+  xrd.cf.fst: |
+    ###########################################################
+    xrootd.fslib -2 libXrdEosFst.so
+    xrootd.async off nosf
+    xrd.network keepalive
+    ###########################################################
+    xrootd.seclib libXrdSec.so
+    sec.protocol unix
+    sec.protocol sss -c /etc/eos.keytab -s /etc/eos.keytab
+    sec.protbind * only unix sss
+    ###########################################################
+    all.export / nolock
+    all.trace none
+    all.manager localhost 2131
+    #ofs.trace open
+    ###########################################################
+    xrd.port 1095
+    ofs.persist off
+    ofs.osslib libEosFstOss.so
+    ofs.tpc pgm /usr/bin/xrdcp
+    ###########################################################
+    # this URL can be overwritten by EOS_BROKER_URL defined /etc/sysconfig/xrd
+    fstofs.broker root://eos-mq.eoscluster.cern.ch:1097//eos/
+    fstofs.autoboot true
+    fstofs.quotainterval 10
+    fstofs.metalog /var/eos/md/
+    fstofs.fmddict /var/eos/md/fstfmd.dict
+    fstofs.qdbpassword_file /etc/eos.keytab
+    ###########################################################
+
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: {{ include "fst.fullname" . }}-cfgmap-sysconfig-eos
+  labels:
+    {{- include "fst.labels" . | nindent 4 }}
+data:
+  # ************************************************************************ #
+  # EOS, the CERN Disk Storage System - Copyright (C) 2011 CERN/Switzerland  #
+  # ************************************************************************ #
+  # Environment variables from /etc/sysconfig/eos                            #
+  # ************************************************************************ #
+  # Should we run with another limit on the core file size other than the default?
+  DAEMON_COREFILE_LIMIT: unlimited
+  # Disable the KRB5 replay cache
+  KRB5RCACHETYPE: none
+  # Skip hostname match for SSS authentication in docker setup
+  # TODO: work around k8s setup issues. This should *NOT* be enabled in production
+  EOS_SKIP_SSS_HOSTNAME_MATCH: !!integer 1
+  # What roles should the xroot daemon run for.
+  # TODO: Shouldn't we just set the role played by this very container?
+  XRD_ROLES: "mq sync mgm fst1 fst2 fst3 fst4 fst5 fst6"
+  
+  # ------------------------------------------------------------------
+  # EOS Configuration
+  # ------------------------------------------------------------------
+  # User std::shared_timed_mutex instead of the pthread_rwlock_*
+  EOS_USE_SHARED_MUTEX: !!integer 1
+  # The EOS instance name
+  EOS_INSTANCE_NAME: eosdockertest
+  # The EOS configuration to load after daemon start
+  EOS_AUTOLOAD_CONFIG: default
+  # The EOS broker URL 
+  EOS_BROKER_URL: root://eos-mq-0.eos-mq.{{ .Release.Namespace }}.svc.cluster.local:1097//eos/
+  # The EOS host geo location tag used to sort hosts into geographical (rack) locations 
+  EOS_GEOTAG: "docker::test"
+  # The fully qualified hostname of MGM master1
+  EOS_MGM_MASTER1: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
+  # The fully qualified hostname of MGM master2
+  EOS_MGM_MASTER2: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
+  # The alias which selects master 1 or 2
+  EOS_MGM_ALIAS: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
+  # The mail notification in case of fail-over
+  #EOS_MAIL_CC: "apeters@mail.cern.ch"
+  #EOS_NOTIFY: "mail -s `date +%s`-`hostname`-eos-notify $EOS_MAIL_CC"
+  # Allow UTF-8 path names excluding only CR,LF
+  EOS_UTF8: ""
+  # Enable QoS support
+  EOS_ENABLE_QOS: ""
+  # Enable Converter Engine
+  EOS_CONVERTER_DRIVER: !!integer 1
+  # Enable core dumps initiated internally 
+  #EOS_CORE_DUMP
+  # Disable shutdown/signal handlers for debugging
+  #EOS_NO_SHUTDOWN
+  
+  #-------------------------------------------------------------------------------
+  # FST Configuration
+  #-------------------------------------------------------------------------------
+  # Stream timeout for operations
+  #EOS_FST_STREAM_TIMEOUT: 300
+  # Specify in seconds how often FSTs should query for new delete operations
+  # Set the polling interval for deletions to 5 seconds for the rm tests to
+  # run faster. This controls how often the FTS request deletions from the MGM.
+  EOS_FST_DELETE_QUERY_INTERVAL: !!integer 5
+  # Number of threads for transfer operations (Balance, Drain or Transfer actions)
+  EOS_FST_TRANSFER_THREAD_POOL: !!integer 20
+  
+  #-------------------------------------------------------------------------------
+  # FST External Storage Configuration
+  #-------------------------------------------------------------------------------
+  # Set number of connection retries
+  EOS_FST_CONNECTION_RETRY: !!integer 1
+  # Set S3 access credentials
+  #EOS_FST_S3_ACCESS_KEY: ""
+  #EOS_FST_S3_SECRET_KEY: ""
+  # Set S3 theoretical storage size
+  EOS_FST_S3_STORAGE_SIZE: !!integer 20000000000
+  # Set HTTPS X509 certificate path
+  #EOS_FST_HTTPS_X509_CERTIFICATE_PATH: ""
+  
+  # ------------------------------------------------------------------
+  # FUSE Configuration
+  # ------------------------------------------------------------------
+  # The mount directory for 'eosd' 
+  EOS_FUSE_MOUNTDIR: /eos/
+  # The MGM host from where to do the initial mount
+  EOS_FUSE_MGM_ALIAS: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
+  # Enable FUSE debugging mode (default off)
+  #EOS_FUSE_DEBUG: 1
+  # Disable parallel IO mode (default on)
+  #EOS_FUSE_NOPIO: 1
+  # Disable multi-threading in FUSE (default on)
+  #EOS_FUSE_NO_MT: 1
+  
+  # ------------------------------------------------------------------
+  # HTTPD Configuration
+  # ------------------------------------------------------------------
+  # Enable multi-threaded httpd
+  EOS_HTTP_THREADPOOL: "epoll"
+  EOS_HTTP_THREADPOOL_SIZE: !!integer 16
+  
+  #-------------------------------------------------------------------------------
+  # GRPC Configuration
+  #-------------------------------------------------------------------------------
+  # GRPC port - set to 0 to disable GRPC
+  EOS_MGM_GRPC_PORT: !!integer 50051
+  
+  # ------------------------------------------------------------------
+  # Federation Configuration
+  # ------------------------------------------------------------------
+  # The host[:port] name of the meta manager (global redirector)
+  #EOS_FED_MANAGER: eos.cern.ch:1094
+  # The port of the PSS xrootd server
+  #EOS_PSS_PORT: 1098
+  # The hostname[:port] of the EOS MGM service
+  #EOS_PSS_MGM: $EOS_MGM_ALIAS:1094
+  # The path which should be proxied (/ for all)
+  #EOS_PSS_PATH: /
+  
+  # ------------------------------------------------------------------
+  # Test Configuration
+  # ------------------------------------------------------------------
+  # mail notification for failed tests
+  #EOS_TEST_MAILNOTIFY: apeters@mail.cern.ch
+  # SMS notification for failed tests
+  #EOS_TEST_GSMNOTIFY: "0041764875002@mail2sms.cern.ch"
+  # Instance name :  name of directory at deepness 2 /eos/<instance>/
+  #EOS_TEST_INSTANCE: "dev"
+  # MGM host redirector
+  #EOS_TEST_REDIRECTOR: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.loca
+  # local test output directory
+  #EOS_TEST_TESTSYS: /tmp/eos-instance-test
+  # time to lock re-sending of SMS for consecutively failing tests
+  #EOS_TEST_GSMLOCKTIME: 3600
+  # max. time given to the test to finish
+  #EOS_TEST_TESTTIMESLICE: 300
+
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: {{ include "fst.fullname" . }}-cfgmap-fst-init
+  labels:
+    {{- include "fst.labels" . | nindent 4 }}
+data:
+  fst_init.sh: |
     #!/bin/bash
 
-    # sysconfig
-    sed -i 's/eos-mgm1.eoscluster.cern.ch/eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/sysconfig/eos
-    sed -i 's/eos-mq.eoscluster.cern.ch/eos-mq-0.eos-mq.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/sysconfig/eos
-    sed -i 's/eostest.cern.ch/eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/sysconfig/eos
+    handle_exit_condition () {
+      local rc=$1
+      local text=$2
 
-    # fuse
-    sed -i 's/eos-mgm1.eoscluster.cern.ch/eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/eos/fuse*.conf
+      if [ $rc -ne 0 ]; then
+        echo "  ✗ $text. Aborting."
+        exit 1
+      else
+        echo "  ✓ Success!"
+      fi
+    }
 
-    # krb - @todo change to actual kdc fqdn in krb5.conf file
-    sed -i 's/eos-kdc.eoscluster.cern.ch/eos-kdc.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/krb5.conf
-    [ -f /kdc_mit.sh ] && sed -i 's/eos-mgm1.eoscluster.cern.ch/eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local/g' /kdc_mit.sh || true
-    [ -f /kdc.sh ] && sed -i 's/eos-mgm1.eoscluster.cern.ch/eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local/g' /kdc.sh || true
 
-    # mgm
-    sed -i 's/eos-qdb.eoscluster.cern.ch/eos-qdb-0.eos-qdb.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/xrd.cf.*
+    # TODO: Improve logging
+    # TODO: Improve checks
 
-    # fst
-    sed -i 's/eos-mgm1.eoscluster.cern.ch/eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local/g' /eos_fst_setup.sh
-    sed -i 's/eos-mq.eoscluster.cern.ch/eos-mq-0.eos-mq.{{ .Release.Namespace }}.svc.cluster.local/g' /etc/xrd.cf.*
-    echo 'fstofs.qdbcluster eos-qdb-0.eos-qdb.{{ .Release.Namespace }}.svc.cluster.local:7777' >> /etc/xrd.cf.fst
+    # TODO: Meta info such
+    #   - space
+    #   - config (rw//ro)
+    #   - geotag
+    #   should all be values and not hardcoded
 
-    # use Quarkdb
-    # sed -i 's/libEosNsInMemory/libEosNsQuarkdb/g' /etc/xrd.cf.mgm
+    # Start the FST process in background so that we can run other commands
+    echo "INFO: Starting FST..."
+    /usr/bin/xrootd -n fst -c /etc/xrd.cf.fst -m -b -Rdaemon >/dev/null 2>&1
 
-    # if using multiple MGMs
-    # echo 'export EOS_USE_QDB_MASTER=1' >> /etc/sysconfig/eos
-    # echo 'mgmofs.cfgtype quarkdb' >> /etc/xrd.cf.mgm
+    ## TODO: Check the MGM is online before proceeding
+    ## # Wait for the FST to be online
+    ## echo "INFO: Waiting for the FST to be online..."
+    ## max_wait=60
+    ## sleep=5
+    ## start_time=$(date +%s)
+    ## rc=-1
+    ## while [ $rc -ne 0 ];
+    ## do
+    ##   timeout --preserve-status $sleep eos ns >/dev/null 2>&1
+    ##   rc=$?
+    ##   sleep $sleep
 
-    # if persistent volumes are attached, let fst data be on persistent volumes
-    # sed -i 's@DATADIR=/home/data/@DATADIR=/volumes/mnt/home/data/@g' eos_fst_setup.sh eos_setup.sh
+    ##   # Bail out after max_wait
+    ##   tot_wait=$(($(date +%s)-start_time))
+    ##   echo "        $tot_wait seconds... (timeout at $max_wait)"
+    ##   if [ $tot_wait -ge $max_wait ]; then
+    ##     echo "ERROR: MGM not reachable after $tot_wait secs. Giving up."
+    ##     exit 1
+    ##   fi
+    ## done
+    ## echo "INFO: MGM is online."
 
-    # test scripts.
-    sed -i 's/eos-mq.eoscluster.cern.ch/eos-mq-0/g' /usr/sbin/eos-instance-test-ci # @todo tmp, then re-code the files
-    # testing 'eos-drain-test' because it is not included in eos ubuntu-based images
-    [ -f /usr/sbin/eos-drain-test ] && sed -i 's/eos-fst4.eoscluster.cern.ch/eos-fst4.eos-fst4.{{ .Release.Namespace }}.svc.cluster.local/g' /usr/sbin/eos-drain-test || true
 
-    # set the geotag and instance name (optional)
-    # sed -i 's/docker/kuber/g' /etc/sysconfig/eos
-    # sed -i 's/docker/kuber/g' /eos_mgm_fs_setup.sh
+    # TODO: Improve here!!
+    id=999
+    UUID=fst${id}
+    DATADIR=/fst_storage
+    SPACE=default
+    CONFIG=rw
+    GEOTAG="docker::test"       # This is duplicated in /etc/eos/sysconfig
+    # TODO
+
+    # If there is an eos fsid || fsuuid, bail out
+    if [ -f $DATADIR/.eosfsid ] || [ -f $DATADIR/.eosfsuuid ]; then
+      echo "FS IDs already exist. Not cofiguring any further"
+      exit 0
+    fi
+
+
+    ### Configure filesystem identifiers
+    echo "$UUID" > $DATADIR/.eosfsuuid
+    echo "${id}" > $DATADIR/.eosfsid
+
+    ### Register space (!! THIS IS A BUG !!)
+    # TODO: BUG!
+    eos -r 0 0 -b space define default
+    eos -r 0 0 -b space set default on
+    # TODO: BUG!
+
+    ### Register filesystem
+    eos -r 0 0 -b fs add -m ${id} $UUID `hostname -f`:1095 $DATADIR default $CONFIG
+    eos -r 0 0 -b node set `hostname -f`:1095 on
+    eos -r 0 0 -b boot ${id}
+
+    exit 0
