mgm: Init container to configure authentication essentials

diff --git a/mgm/templates/configmap.yaml b/mgm/templates/configmap.yaml
--- a/mgm/templates/configmap.yaml
+++ b/mgm/templates/configmap.yaml
@@ -231,3 +231,85 @@ data:
   # max. time given to the test to finish
   #EOS_TEST_TESTTIMESLICE: 300
 
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: {{ include "mgm.fullname" . }}-cfgmap-auth-init
+  labels:
+    {{- include "mgm.labels" . | nindent 4 }}
+data:
+  auth_init.sh: |
+    #!/bin/bash
+
+    handle_exit_condition () {
+      local rc=$1
+      local text=$2
+
+      if [ $rc -ne 0 ]; then
+        echo "  ✗ $text. Aborting."
+        exit 1
+      else
+        echo "  ✓ Success!"
+      fi
+    }
+
+
+    # Check if a previous configuration already exists
+    #   If so, don't touch.
+    echo "INFO: Looking for previous EOS configurations..."
+    if [ -d /var/eos/config/ ]; then
+      if [ $(find /var/eos/config -maxdepth 1 -type d | wc -l) -gt 1 ]; then
+        echo "  ✓ EOS configurations found. Exiting."
+        exit 0
+      fi
+    fi
+    echo "  ✓ None found. Configuring..."
+
+    # Start the MGM process in background so that we can run other commands
+    echo "INFO: Starting MGM..."
+    /usr/bin/xrootd -n mgm -c /etc/xrd.cf.mgm -m -b -Rdaemon >/dev/null 2>&1
+
+    # Wait for the MGM to be online
+    echo "INFO: Waiting for the MGM to be online..."
+    max_wait=60
+    sleep=5
+    start_time=$(date +%s)
+    rc=-1
+    while [ $rc -ne 0 ];
+    do
+      timeout --preserve-status $sleep eos ns >/dev/null 2>&1
+      rc=$?
+      sleep $sleep
+
+      # Bail out after max_wait
+      tot_wait=$(($(date +%s)-start_time))
+      echo "        $tot_wait seconds... (timeout at $max_wait)"
+      if [ $tot_wait -ge $max_wait ]; then
+        echo "ERROR: MGM not reachable after $tot_wait secs. Giving up."
+        exit 1
+      fi
+    done
+    echo "INFO: MGM is online."
+
+    # Enable SSS
+    echo "INFO: Enabling SSS..."
+    eos -b vid enable sss
+    handle_exit_condition $? "Error enabling SSS"
+
+    # Give sudo powers to daemon user
+    echo "INFO: Adding user 'daemon' to sudoers..."
+    eos -b vid set membership daemon +sudo
+    handle_exit_condition $? "Error adding user daemon to sudoers"
+
+    echo "INFO: Saving configuration..."
+    eos -b config save deafult -f
+    handle_exit_condition $? "Error saving configuration"
+
+    echo "INFO: EOS autentication initialized successfully."
+    exit 0
+
+
+    # useradd eos_k8s_admin
+    # eos -b vid set membership eos_k8s_admin +sudo
+
